apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: base
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: base-0.1.0
  name: production-release-name-base
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: base
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: base-0.1.0
  name: production-release-name-base
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: base
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: base
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: base-0.1.0
  name: production-release-name-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: base
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/name: base
    spec:
      containers:
      - image: nginx:1.16.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: base
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
      - image: mysql:5.6
        name: addmysql
        resources:
          limits:
            memory: 1250Mi
          requests:
            memory: 1250Mi
      serviceAccountName: production-release-name-base
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: base
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: base-0.1.0
  name: production-release-name-base-test-connection
spec:
  containers:
  - args:
    - release-name-base:80
    command:
    - wget
    image: busybox
    name: wget
  restartPolicy: Never
